[tool.ruff]
# Exclude common directories
exclude = [
    ".git",
    ".venv", 
    "__pycache__",
    "build",
    "dist",
    ".pytest_cache",
]

line-length = 88
target-version = "py313"

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "W", "I"]
ignore = [
    "B008",  # Do not perform function call in argument defaults - FastAPI pattern is correct
    "E501",  # Line too long - handled by formatter
    "F401",  # Imported but unused - allow for explicit imports
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["app"]
force-single-line = false
