# Ruff configuration
line-length = 88
target-version = "py313"

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
[lint]
select = ["E", "F", "W", "I", "B", "UP"]
ignore = [
    "B008",  # Do not perform function call in argument defaults - FastAPI pattern
    "E501",  # Line too long - handled by formatter
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude common directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    ".pytest_cache",
]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
known-first-party = ["app"]
force-single-line = false
